spring:
  application:
    name: purchase-transaction-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wexPurchases}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

treasury:
  api:
    base-url: ${TREASURY_API_BASE_URL:https://api.fiscaldata.treasury.gov/services/api/fiscal_service}
    path: /v1/accounting/od/rates_of_exchange
    page-size: 500
    connect-timeout-ms: 2000
    read-timeout-ms: 5000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
